AWSTemplateFormatVersion: '2010-09-09'
Description: "Create an S3 Bucket and EC2 Volume"
Resources:
    myS3Bucket1:
        Type: "AWS::S3::Bucket"
        Properties:
            BucketName: "bucketnamesneedtobeuniquemybucket1"
    myS3Bucket2:
        Type: "AWS::S3::Bucket"
        DeletionPolicy: "Retain"
        Properties:
            BucketName: "bucketnamesneedtobeuniquemybucket2"
    myVolume:
        Type: "AWS::EC2::Volume"
        DeletionPolicy: "Snapshot"
        Properties:
            AvailabilityZone: "us-east-2a"
            Size: "100"
